server:
  port: 9527
 
spring:
  application:
    name: gateway1
    
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #注册中心地址
        
#动态路由
    gateway:
      discovery:
        locator:
          enabled: true #开始路由,利用微服务名进行路由    
      routes:
        - id: redP1_routh          #路由id,没有固定规则但是要求唯一，建议配合服务名
          uri:  lb://redP1       #匹配后提供的服务的路由地址
          predicates:              #断言，路径相匹配的进行路由
            - Path=/redP1/**
            
        - id: redC1_routh          #路由id,没有固定规则但是要求唯一，建议配合服务名
          uri:  lb://redC1       #匹配后提供的服务的路由地址
          predicates:              #断言，路径相匹配的进行路由
            - Path=/redC1/**
        
        
logging:
  config: classpath:logback.xml